### ISSUE TITLE
Could you provide the GTA pretrained model ?

### ISSUE THREAD

**Issue by lianghao12138** [SysCV/qd-3dt#13]
Hi, I'm trying to train model on Kitti dataset, but I cannot find the GTA pretrained model. Could you provide it ? 
Thanks !

**Comment by eborboihuc** [comment]
Thank you for trying out our code. 
We would recommend using our KITTI pretrained weight directly. We don't have a plan in releasing GTA pretrained weight now.

**Comment by lianghao12138** [comment]
> Thank you for trying out our code.
> We would recommend using our KITTI pretrained weight directly. We don't have a plan in releasing GTA pretrained weight now.

What a pity !
Anyway, thank you !
