### ISSUE TITLE
Test the model  on a new dataset/images

### ISSUE THREAD

**Issue by golnazhabibi3** [SysCV/qd-3dt#16]
Hi, Thanks for your impressive work! Could you help me how I can run your code on a sample image? Thanks

**Comment by tobiasfshr** [comment]
Hi, please refer to the discussions for how to extend the code to run it on a sample image.

**Comment by golnazhabibi3** [comment]
OK, great, could you send me the link to that discussion? I do not find it. Thanks!

**Comment by tobiasfshr** [comment]
e.g. https://github.com/SysCV/qd-3dt/discussions/9

**Comment by golnazhabibi3** [comment]
Thanks for your reply. I tried to make my data format similar to kitti format but I do not have information about the map (oxts in kitti), so when I ignore this value, I am not able to run the inference and it seems detection  depends on the map! so how I can test the algorithm on the data with oxts or it is better I use nuscenes model? Thanks!

**Comment by tobiasfshr** [comment]
our method requires ego pose information, so you will need some estimate of the camera motion. This can be obtained via a sensor, but also via a localization algorithm (stereo / mono).
