### ISSUE TITLE
ModuleNotFoundError: No module named 'qd3dt.version'

### ISSUE THREAD

**Issue by xhangHU** [SysCV/qd-3dt#17]
+ dataset=nuscenes
+ config_path=configs/Nusc/quasi_r101_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_scale_no_filter.py
+ gpu_ids=0
+ gpu_nums=1
+ PY_ARGS='--data_split_prefix train --pure_det'
+ root=.
++ dirname Nusc/quasi_r101_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_scale_no_filter.py
+ folder=work_dirs/Nusc
++ basename -s .py configs/Nusc/quasi_r101_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_scale_no_filter.py
+ config=quasi_r101_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_scale_no_filter
+ cd mmcv
++ pwd
+ export PYTHONPATH=/root/docker2/qd-3dt/mmcv:
+ PYTHONPATH=/root/docker2/qd-3dt/mmcv:
+ cd ..
+ CUDA_VISIBLE_DEVICES=0
+ python3 -u ./tools/test_eval_video_exp.py nuscenes configs/Nusc/quasi_r101_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_scale_no_filter.py ./work_dirs/Nusc/quasi_r101_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_scale_no_filter/latest.pth ./work_dirs/Nusc/quasi_r101_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_scale_no_filter/output/output.pkl --data_split_prefix train --pure_det
Traceback (most recent call last):
  File "./tools/test_eval_video_exp.py", line 10, in <module>
    from qd3dt.datasets import build_dataloader, build_dataset
  File "/root/docker2/qd-3dt/qd3dt/__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'qd3dt.version'

**Comment by xhangHU** [comment]
By the way, I would like to ask, how do I test my own data with the existing model here, and what do I need to do.

**Comment by tobiasfshr** [comment]
Did you follow all instructions in INSTALL.md? Including running install.sh?
Please refer to the discussions on how to run the models on your own data.

**Comment by xhangHU** [comment]
I have understood the above problem, and now there is a new problem, when I use requeirements.txt and requeirements_nusc.txt
There was an error when numpy version 1.18
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
In pip uninstall numpy
After pip install numpy
I got another error
TypeError: expected dtype object, got'numpy.dtype[float64]'

**Comment by xhangHU** [comment]
There are other problems
It will report an error when using motmetrics=1.1.3
ModuleNotFoundError: No module named'motmetrics.math_util'

**Comment by eborboihuc** [comment]
> There are other problems
> It will report an error when using motmetrics=1.1.3
> ModuleNotFoundError: No module named'motmetrics.math_util'

You will only need `motmetrics=1.1.3` when running scripts with nuScenes-related evaluation as mentioned in our [INSTALL.md](https://github.com/SysCV/qd-3dt/blob/main/readme/INSTALL.md#build-new-virtualenv-for-nuscenes-3d-tracking-evaluation). Otherwise, please use `motmetrics=1.2.0`.

**Comment by xhangHU** [comment]
> > There are other problems
> > It will report an error when using motmetrics=1.1.3
> > ModuleNotFoundError: No module named'motmetrics.math_util'
> 
> You will only need `motmetrics=1.1.3` when running scripts with nuScenes-related evaluation as mentioned in our [INSTALL.md](https://github.com/SysCV/qd-3dt/blob/main/readme/INSTALL.md#build-new-virtualenv-for-nuscenes-3d-tracking-evaluation). Otherwise, please use `motmetrics=1.2.0`.

When I use use motmetrics=1.2.0, with the numpy version problem mentioned earlier.

**Comment by eborboihuc** [comment]
> I have understood the above problem, and now there is a new problem, when I use requeirements.txt and requeirements_nusc.txt
> There was an error when numpy version 1.18
> ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
> In pip uninstall numpy
> After pip install numpy
> I got another error
> TypeError: expected dtype object, got'numpy.dtype[float64]'

Cool, it seems you have checked issue #3  at this [comment](https://github.com/SysCV/qd-3dt/issues/3#issuecomment-815019623)

Can you try to install `numpy==1.18.2`? With that, it works with `numba==0.48.0` and `motmetrics==1.2.0`.
Also, it would help us to know more about your issue if you can provide the error message.

**Comment by xhangHU** [comment]
> > I have understood the above problem, and now there is a new problem, when I use requeirements.txt and requeirements_nusc.txt
> > There was an error when numpy version 1.18
> > ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
> > In pip uninstall numpy
> > After pip install numpy
> > I got another error
> > TypeError: expected dtype object, got'numpy.dtype[float64]'
> 
> Cool, it seems you have checked issue #3 at this [comment](https://github.com/SysCV/qd-3dt/issues/3#issuecomment-815019623)
> 
> Can you try to install `numpy==1.18.2`? With that, it works with `numba==0.48.0` and `motmetrics==1.2.0`.
> Also, it would help us to know more about your issue if you can provide the error message.

Unfortunately, I use numpy==1.18.2 numba==0.48.0 and motmetrics==1.2.0
Still prompted
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
I try pip uninstall numpy
pip install numpy
Still got this error
TypeError: expected dtype object, got'numpy.dtype[float64]'

**Comment by eborboihuc** [comment]
Can you provide the output of the commands:
```sh
pip list
conda list # if you use it
```
It helps us to know more about what you facing with more detailed information.

Also, please check if your `pycocotools` version. Mine works in `2.0.1` and `2.0.2`. You might want to do the following
```sh
pip uninstall pycocotools
pip install pycocotools
```
to see if you can get rid of the PyObject issue.

**Comment by xhangHU** [comment]
here is conda list:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
absl-py                   0.13.0                   pypi_0    pypi
addict                    2.3.0                    pypi_0    pypi
anyio                     3.2.1                    pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
astroid                   2.5                      pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bleach                    3.3.0                    pypi_0    pypi
ca-certificates           2021.5.25            h06a4308_1
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30        py37h06a4308_0
cffi                      1.14.5                   pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.16                  pypi_0    pypi
debugpy                   1.3.0                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
descartes                 1.1.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
fire                      0.4.0                    pypi_0    pypi
flake8                    3.9.2                    pypi_0    pypi
flake8-import-order       0.18.1                   pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
google-auth               1.32.1                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        3.10.1                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
ipykernel                 6.0.0                    pypi_0    pypi
ipython                   7.25.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
isort                     4.3.21                   pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    3.0.1                    pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
json5                     0.9.6                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyter-packaging         0.10.3                   pypi_0    pypi
jupyter-server            1.9.0                    pypi_0    pypi
jupyterlab                3.0.16                   pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-server         2.6.0                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
lap                       0.4.0                    pypi_0    pypi
lazy-object-proxy         1.6.0                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9
libedit                   3.1.20210216         h27cfd23_1
libffi                    3.2.1             hf484d3e_1007
libgcc-ng                 9.3.0               h5101ec6_17
libgomp                   9.3.0               h5101ec6_17
libstdcxx-ng              9.3.0               hd4cf53a_17
llvmlite                  0.31.0                   pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.2.1                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mmcv                      1.3.8                    pypi_0    pypi
motmetrics                1.2.0                    pypi_0    pypi
munkres                   1.1.2                    pypi_0    pypi
nbclassic                 0.3.1                    pypi_0    pypi
nbclient                  0.5.3                    pypi_0    pypi
nbconvert                 6.1.0                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1
nest-asyncio              1.5.1                    pypi_0    pypi
networkx                  2.5.1                    pypi_0    pypi
notebook                  6.4.0                    pypi_0    pypi
numba                     0.48.0                   pypi_0    pypi
numpy                     1.21.0                   pypi_0    pypi
numpy-quaternion          2020.4.24.9.29.7          pypi_0    pypi
nuscenes-devkit           1.1.1                    pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
open3d                    0.10.0.0                 pypi_0    pypi
opencv-python             4.2.0.34                 pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.5                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.3.0                    pypi_0    pypi
pip                       21.1.3                   pypi_0    pypi
pluggy                    0.13.1                   pypi_0    pypi
prometheus-client         0.11.0                   pypi_0    pypi
prompt-toolkit            3.0.19                   pypi_0    pypi
protobuf                  3.17.3                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
py                        1.10.0                   pypi_0    pypi
py-cpuinfo                8.0.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycairo                   1.20.1                   pypi_0    pypi
pycocotools               2.0.2                    pypi_0    pypi
pycodestyle               2.7.0                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pyflakes                  2.3.1                    pypi_0    pypi
pygments                  2.9.0                    pypi_0    pypi
pygobject                 3.40.1                   pypi_0    pypi
pylint                    2.5.3                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyrsistent                0.18.0                   pypi_0    pypi
pytest                    6.1.0                    pypi_0    pypi
pytest-benchmark          3.4.1                    pypi_0    pypi
python                    3.7.6                h0371630_2
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.1.0                   pypi_0    pypi
qd3dt                     0.6.0+9f7c82a             dev_0    <develop>
qtconsole                 5.1.1                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  7.0                  h7b6447c_5
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
requests-unixsocket       0.2.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
seaborn                   0.10.0                   pypi_0    pypi
send2trash                1.7.1                    pypi_0    pypi
setuptools                57.0.0                   pypi_0    pypi
shapely                   1.7.1                    pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
sniffio                   1.2.0                    pypi_0    pypi
sqlite                    3.33.0               h62c20be_0
tensorboard               1.15.0                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorboardx              2.0                      pypi_0    pypi
tensorflow-estimator      1.15.1                   pypi_0    pypi
tensorflow-gpu            1.15.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.10.1                   pypi_0    pypi
terminaltables            3.1.0                    pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tifffile                  2021.6.14                pypi_0    pypi
tk                        8.6.10               hbc83047_0
toml                      0.10.2                   pypi_0    pypi
tomlkit                   0.7.2                    pypi_0    pypi
torch                     1.4.0                    pypi_0    pypi
torchvision               0.5.0                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.45.0                   pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typed-ast                 1.4.3                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
utm                       0.5.0                    pypi_0    pypi
waymo-open-dataset-tf-1-15-0 1.2.0                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.1.0                    pypi_0    pypi
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.2                   pypi_0    pypi
widgetsnbextension        3.5.1                    pypi_0    pypi
wrapt                     1.12.1                   pypi_0    pypi
xmltodict                 0.12.0                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0
yapf                      0.30.0                   pypi_0    pypi
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3




and pip list
Package                      Version             Location
---------------------------- ------------------- --------------------
absl-py                      0.13.0
addict                       2.3.0
anyio                        3.2.1
argon2-cffi                  20.1.0
astor                        0.8.1
astroid                      2.5
astunparse                   1.6.3
async-generator              1.10
attrs                        21.2.0
Babel                        2.9.1
backcall                     0.2.0
bleach                       3.3.0
cached-property              1.5.2
cachetools                   4.2.2
certifi                      2021.5.30
cffi                         1.14.5
chardet                      4.0.0
cycler                       0.10.0
Cython                       0.29.16
debugpy                      1.3.0
decorator                    4.4.2
defusedxml                   0.7.1
deprecation                  2.1.0
descartes                    1.1.0
entrypoints                  0.3
filterpy                     1.4.5
fire                         0.4.0
flake8                       3.9.2
flake8-import-order          0.18.1
flatbuffers                  1.12
gast                         0.2.2
google-auth                  1.32.1
google-auth-oauthlib         0.4.4
google-pasta                 0.2.0
grpcio                       1.34.1
h5py                         3.1.0
idna                         2.10
imageio                      2.9.0
importlib-metadata           3.10.1
iniconfig                    1.1.1
ipykernel                    6.0.0
ipython                      7.25.0
ipython-genutils             0.2.0
ipywidgets                   7.6.3
isort                        4.3.21
jedi                         0.18.0
Jinja2                       3.0.1
joblib                       1.0.1
json5                        0.9.6
jsonschema                   3.2.0
jupyter                      1.0.0
jupyter-client               6.1.12
jupyter-console              6.4.0
jupyter-core                 4.7.1
jupyter-packaging            0.10.3
jupyter-server               1.9.0
jupyterlab                   3.0.16
jupyterlab-pygments          0.1.2
jupyterlab-server            2.6.0
jupyterlab-widgets           1.0.0
Keras-Applications           1.0.8
keras-nightly                2.5.0.dev2021032900
Keras-Preprocessing          1.1.2
kiwisolver                   1.3.1
lap                          0.4.0
lazy-object-proxy            1.6.0
llvmlite                     0.31.0
Markdown                     3.3.4
MarkupSafe                   2.0.1
matplotlib                   3.2.1
matplotlib-inline            0.1.2
mccabe                       0.6.1
mistune                      0.8.4
mmcv                         1.3.8
motmetrics                   1.2.0
munkres                      1.1.2
nbclassic                    0.3.1
nbclient                     0.5.3
nbconvert                    6.1.0
nbformat                     5.1.3
nest-asyncio                 1.5.1
networkx                     2.5.1
notebook                     6.4.0
numba                        0.48.0
numpy                        1.21.0
numpy-quaternion             2020.4.24.9.29.7
nuscenes-devkit              1.1.1
oauthlib                     3.1.1
open3d                       0.10.0.0
opencv-python                4.2.0.34
opt-einsum                   3.3.0
packaging                    20.9
pandas                       1.2.5
pandocfilters                1.4.3
parso                        0.8.2
pexpect                      4.8.0
pickleshare                  0.7.5
Pillow                       8.3.0
pip                          21.1.3
pluggy                       0.13.1
prometheus-client            0.11.0
prompt-toolkit               3.0.19
protobuf                     3.17.3
ptyprocess                   0.7.0
py                           1.10.0
py-cpuinfo                   8.0.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pycairo                      1.20.1
pycocotools                  2.0.2
pycodestyle                  2.7.0
pycparser                    2.20
pyflakes                     2.3.1
Pygments                     2.9.0
PyGObject                    3.40.1
pylint                       2.5.3
pyparsing                    2.4.7
pyquaternion                 0.9.9
pyrsistent                   0.18.0
pytest                       6.1.0
pytest-benchmark             3.4.1
python-dateutil              2.8.1
pytz                         2021.1
PyWavelets                   1.1.1
PyYAML                       5.4.1
pyzmq                        22.1.0
qd3dt                        0.6.0+9f7c82a       /root/docker2/qd-3dt
qtconsole                    5.1.1
QtPy                         1.9.0
requests                     2.25.1
requests-oauthlib            1.3.0
requests-unixsocket          0.2.0
rsa                          4.7.2
scikit-image                 0.17.2
scikit-learn                 0.23.1
scipy                        1.4.1
seaborn                      0.10.0
Send2Trash                   1.7.1
setuptools                   57.0.0
Shapely                      1.7.1
six                          1.15.0
sklearn                      0.0
sniffio                      1.2.0
tensorboard                  1.15.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.0
tensorboardX                 2.0
tensorflow-estimator         1.15.1
tensorflow-gpu               1.15.0
termcolor                    1.1.0
terminado                    0.10.1
terminaltables               3.1.0
testpath                     0.5.0
threadpoolctl                2.1.0
tifffile                     2021.6.14
toml                         0.10.2
tomlkit                      0.7.2
torch                        1.4.0
torchvision                  0.5.0
tornado                      6.1
tqdm                         4.45.0
traitlets                    5.0.5
typed-ast                    1.4.3
typing-extensions            3.7.4.3
urllib3                      1.26.6
utm                          0.5.0
waymo-open-dataset-tf-1-15-0 1.2.0
wcwidth                      0.2.5
webencodings                 0.5.1
websocket-client             1.1.0
Werkzeug                     2.0.1
wheel                        0.36.2
widgetsnbextension           3.5.1
wrapt                        1.12.1
xmltodict                    0.12.0
yapf                         0.30.0
zipp                         3.4.1

My pycocotools verson is 2.0.2

**Comment by xhangHU** [comment]
Is it because I am running on the server? I am not using desktop-grade Ubuntu.

**Comment by xhangHU** [comment]
I solved this problem by
python3 -m pip install numba==0.53.0
Thank you!

**Comment by eborboihuc** [comment]
Great to hear that!

After some searching, I also noticed that others using `numba` have this issue [[1](https://github.com/numba/numba/issues/6041)] and some others [[2](https://github.com/uma-pi1/kge/issues/198)] solve the issue just like you.
