### ISSUE TITLE
KF3D in ablation study

### ISSUE THREAD

**Issue by hhhmoan** [SysCV/qd-3dt#18]
Hi,
    Have read your paper, i find that with kalman filter you achieve a high performance. Could you release the KF3D method? 
![image](https://user-images.githubusercontent.com/8188952/125163543-2f643980-e1c0-11eb-8dfe-2d619f86edb3.png)

Thank you

**Comment by tobiasfshr** [comment]
Hi, you can switch to the Kalman Filter model by using KalmanBox3DTracker instead of e.g. Embedding3DBEVMotionUncertaintyTracker in your config (test_cfg -> track -> type). No need to release any additional models. :)
