### ISSUE TITLE
  How to use on 3070 graphics card？

### ISSUE THREAD

**Issue by digtial** [SysCV/qd-3dt#20]
My 3070 graphics card doesn't support cuda10.1. When I compile qd-3dt, it will report an error.

**Comment by digtial** [comment]
I have solved this issue.

**Comment by LawrenceXu13467** [comment]
Hi digitial,

Glad you figured it out. Would you please share how you solved the issue?
I am having a similar situation with "ValueError: Unknown CUDA arch (8.6) or GPU not supported" on RTX 3090.
Thank you very much.

Sincerely,
Ziheng

**Comment by LawrenceXu13467** [comment]
The environment I have:
RTX 3090
torch 1.8.0
cuda 11.3
Thanks

**Comment by alfinnurhalim** [comment]
Hi digital. would you mind sharing with us how did you solve it?
