### ISSUE TITLE
Information about 2D bounding boxes

### ISSUE THREAD

**Issue by xhangHU** [SysCV/qd-3dt#24]
In the final result, the generated txt contains 3d information. I would like to know how the result of'(a) part' mentioned in the picture of your paper is transferred to'(b) part', you can tell How is this part of my content reflected in the code?

**Comment by xhangHU** [comment]
In other words, at which step is the result of the 2D bounding box stored, because I want to replace the 2D bounding box information, thank you for your help

**Comment by RoyYang0714** [comment]
Hi, our result of the 2D bounding boxes is generated [here](https://github.com/SysCV/qd-3dt/blob/main/qd3dt/models/detectrackers/quasi_dense_3d_sep_uncertainty.py#L201) during training and [here](https://github.com/SysCV/qd-3dt/blob/main/qd3dt/models/detectrackers/quasi_dense_3d_sep_uncertainty.py#L400) during inference. You can check more details by tracing our code of bbox head.
