### ISSUE TITLE
ValueError: current limit exceeds maximum limit

### ISSUE THREAD

**Issue by husamhamu** [SysCV/qd-3dt#27]
Hi, thanks for the great work.
I am getting the following error:
`Traceback (most recent call last):
  File "./tools/test_eval_video_exp.py", line 10, in <module>
    from qd3dt.datasets import build_dataloader, build_dataset
  File "/home/husam/qd-3dt/qd3dt/datasets/__init__.py", line 3, in <module>
    from .loader import GroupSampler, DistributedGroupSampler, build_dataloader
  File "/home/husam/qd-3dt/qd3dt/datasets/loader/__init__.py", line 1, in <module>
    from .build_loader import build_dataloader
  File "/home/husam/qd-3dt/qd3dt/datasets/loader/build_loader.py", line 15, in <module>
    resource.setrlimit(resource.RLIMIT_NOFILE, (65535, rlimit[1]))
ValueError: current limit exceeds maximum limit`

when trying to reproduce your results on the KITTI data set using the command:
`./scripts/test_eval_exp.sh kitti configs/KITTI/quasi_dla34_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_subtrain_mod_anchor_ratio_small_strides_GTA.py 0 1 --data_split_prefix subval_dla34_regress_GTA_VeloLSTM --add_ablation_exp all`

I carefully followed the steps in the GETTING_STARTED.md file and I think I was successful with the previous steps. And now I don't know why I am getting this error ?

**Comment by RoyYang0714** [comment]
Hi, it seems that your machine can't use 65535 as the limit [here](https://github.com/SysCV/qd-3dt/blob/main/qd3dt/datasets/loader/build_loader.py#L15). You can try with a smaller number here to run the code on your device.
