### ISSUE TITLE
How to get tracking_output_train.json and tracking_output_val.json ?

### ISSUE THREAD

**Issue by LittleFlyFish** [SysCV/qd-3dt#43]
Hi I try to reproduce this code following the GETTING_STARTED.md

However, when I try to run 

CUDA_VISIBLE_DEVICES=1 python qd3dt/models/detectrackers/tracker/motion_lstm.py nuscenes train \
--session batch128_min10_seq10_dim7_VeloLSTM \
--min_seq_len 10 --seq_len 10 \
--lstm_model_name VeloLSTM --tracker_model_name KalmanBox3DTracker \
--input_gt_path data/nuscenes/anns/tracking_train.json \
--input_pd_path data/nuscenes/anns/tracking_output_train.json \
--cache_name work_dirs/LSTM/nuscenes_train_pure_det_min10.pkl \
--loc_dim 7 -b 128 --is_plot --show_freq 500

these piece of code, it outcomes error that the two json files are not there. I have checked all the files and generation however I still cannot find these two files, Could you release these two files? That's quite important.

Soft-link pure detection results under data/${DATASET}/anns as **tracking_output_train.json** and **tracking_output_val.json**.

Many appreciations for your help if you could update this issue as soon as possible. I think many people has this issue as well.

**Comment by wanglumeng** [comment]
You may refer to [lstm-motion-model-training](https://github.com/SysCV/qd-3dt/blob/main/readme/GETTING_STARTED.md#lstm-motion-model-training)

Test in a pure_det mode will generate a output.json

**Comment by LittleFlyFish** [comment]
> You may refer to [lstm-motion-model-training](https://github.com/SysCV/qd-3dt/blob/main/readme/GETTING_STARTED.md#lstm-motion-model-training)
> 
> Test in a pure_det mode will generate a output.json
